[package]
name = "origami"
version = "0.1.0"
edition = "2021"

[dependencies]
nova-scotia = {git = "https://github.com/l-adic/Nova-Scotia", rev = "e76ef90440938371c5ac7bbdfecba684deaf89c2" }
nova-snark = "0.23.0"
pasta_curves = "0.5"
serde = "1.0"
serde_json = "1.0.85"
